# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RNIosZxing' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RNIosZxing
platform :ios, '8.0'
pod 'ZXingObjC', '~> 3.6.4'
end
